name: pytest

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ${{ matrix.info.os }}
    strategy:
      matrix:
        info:
          - os: ubuntu-latest
            python: 3.9
            mysql: 8.0
            postgres: 14
          - os: ubuntu-latest
            python: 3.13
            mysql: 8.0
            postgres: 18
          - os: windows-2022
            python: 3.13
            mysql: 5.7
            postgres: 14
    name: ${{matrix.info.os}} ${{ matrix.info.python }} ${{ matrix.info.mysql }} ${{ matrix.info.postgres }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.info.python }}
      with:
        python-version: ${{ matrix.info.python }}

    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ matrix.info.mysql }}

    - name: Setup PostgreSQL
      uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgres-version: "${{ matrix.info.postgres }}"
        username: postgres
        password: postgres
        database: postgres

    - name: Configure PostgreSQL env
      run: |
        echo "PGHOST=localhost" >> $GITHUB_ENV
        echo "PGPORT=5432" >> $GITHUB_ENV
        echo "PGUSER=postgres" >> $GITHUB_ENV
        echo "PGPASSWORD=postgres" >> $GITHUB_ENV

    - name: Test
      run: |
        python -m pip install --upgrade pip
        bash ./ci-test.sh
        bash ./ci-cov.sh
